### ISSUE TITLE
[a11y] Close button is not clickable when ConflictPicker is opened

### ISSUE THREAD

**Issue by emoral435** [nextcloud-libraries/nextcloud-upload#1095]
See: https://github.com/nextcloud/server/pull/43667#issuecomment-1955752207

It seems that the close button on the ConflictPicker is not currently accessible with a mouse cursor. It does seem related to its z-index, so I will investigate this ASAP!

**Comment by susnux** [comment]
I think migrating from NcModal to NcDialog should fix this.

We had this also on photos.
