### ISSUE TITLE
Question: Does `@nextcloud/upload` support multipart upload to S3? Configuration details needed.

### ISSUE THREAD

**Issue by BryanCB1** [nextcloud-libraries/nextcloud-upload#1439]
I am currently using the `@nextcloud/upload` library in my Angular project to handle file uploads to Nextcloud, and I am interested in leveraging multipart upload for large files. My backend is configured to use an S3-compatible storage service, and I would like to confirm the following:

1. Does the `@nextcloud/upload` library support multipart uploads directly to S3 storage? If so, does the library automatically handle the multipart upload process, or are there additional configurations required to enable this feature?

2. If additional configurations are needed, could you provide guidance or examples on how to set them up? Specifically, I am looking for information on any settings related to chunk size, parallel uploads, or custom headers that may be necessary for S3 integration.

I have already configured the Uploader with a chunkSize parameter, but I want to ensure I am taking full advantage of any multipart upload optimizations that may be available.

Thank you for your assistance, and I appreciate the great work you do!

**Comment by edward-ly** [comment]
I believe this has been supported since #925, no? No additional configuration is needed, I think.

**Comment by susnux** [comment]
This library uses the Nextcloud WebDAV endpoints, meaning if you configured your backend correctly it will automatically use multipart upload.
Note that for public pages this is only possible starting with Nextcloud 29.
