### ISSUE TITLE
Add file conflict modal

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud-libraries/nextcloud-upload#569]
![image](https://github.com/nextcloud-libraries/nextcloud-upload/assets/14975046/eb8c9464-6c3e-4814-9d9c-1947513509a0)

**Comment by skjnldsv** [comment]
@nimishavijay @szaimen  I have a few questions

1. We do not have a checkbox component/styling that fits your mockup. The white background is mostly the issue. See screenshot below. NOTE: there is NO way to have that since the checkbox svg have margin we can't handle and applying a white background [would overflow](https://github.com/nextcloud-libraries/nextcloud-upload/assets/14975046/87af25f4-5719-418a-b076-50abee5caf03).
   ![image](https://github.com/nextcloud-libraries/nextcloud-upload/assets/14975046/dfb3b65a-b140-44ab-bc96-f3dc896a1919)
2. I'd like to suggest a wording change for the `Confirm` button. As we're in the middle of a process and we require a user input, I suggest `Continue instead`
  ![image](https://github.com/nextcloud-libraries/nextcloud-upload/assets/14975046/328c5e00-5181-4d03-af2e-19ddbc1c57d5)

**Comment by skjnldsv** [comment]
> * What would "Cancel" do? will it skip the files or cancel the whole upload operation?

Veeery good question!
I would say keep all existing files. So maybe we can use that wording instead? That sounds a bit long though :thinking: 

> * slightly more spacing between the files (in the mockup it is 12px)
> *  slightly more spacing below the file name (in the mockup it is 4px)
> *  16px spacing above and below the hairline

It's in progress :grin: Give me time ahah
____
Here you go! I adjusted the spacing and layout and used the accessible checkboxes component! :)
![image](https://github.com/nextcloud-libraries/nextcloud-upload/assets/14975046/9f6922be-c88f-44bc-a736-ac4895c5a242)

**Comment by skjnldsv** [comment]
The border looks a bit off imho
![image](https://github.com/nextcloud-libraries/nextcloud-upload/assets/14975046/dde8394b-dec7-4322-ae20-d1055af1872e)

**Comment by skjnldsv** [comment]
> True, maybe a border for all preview thumbnails, no border for icons?

I can't differentiate from a preview from an icon returned from server.
I guess we can ignore the border for now then

Done. I also took the liberty to remove the 

## Final screenshots
![image](https://github.com/nextcloud-libraries/nextcloud-upload/assets/14975046/a136732f-3574-47b7-b123-136311d60e3d)

We now support html default validity check
| Normal | Mobile |
|:---------:|:------:|
|![image](https://github.com/nextcloud-libraries/nextcloud-upload/assets/14975046/1f63996b-9c6c-4a6e-bf96-2720625e632d)|![image](https://github.com/nextcloud-libraries/nextcloud-upload/assets/14975046/bc5ce742-a9d1-45b8-b96b-bb1ff3733ced)|

**Comment by nimishavijay** [comment]
Looks great now! :) 

> the title and description and maybe even the buttons to select all should stay on top and not scroll away?

definitely the heading should stay sticky. Description and buttons being sticky sounds great! My worry is that too much content is sticky and not a lot of vertical space that scrolls. Would it be possible to make the heading, description and buttons sticky on larger screens and only the heading sticky on mobile?

**Comment by skjnldsv** [comment]
> Description and buttons being sticky sounds great! My worry is that too much content is sticky and not a lot of vertical space that scrolls. Would it be possible to make the heading, description and buttons sticky on larger screens and only the heading sticky on mobile?

You folks don't like simple things don't you? :see_no_evil: :grin: 
Will do in a few minutes :)

**Comment by skjnldsv** [comment]
Done :)

**Comment by szaimen** [comment]
🎉🎉🎉

**Comment by skjnldsv** [comment]
Check PR in https://github.com/nextcloud/server/pull/39945
