### ISSUE TITLE
Support for chunked upload v2 - S3 multipart upload

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud-libraries/nextcloud-upload#924]
We need to adapt the chunked upload bits to also work with https://github.com/nextcloud/server/pull/27034 

documented in https://github.com/nextcloud/documentation/pull/10740

**Comment by juliushaertl** [comment]
Would be a regression for 28 if we don't do that, I can check this somewhen next week.

**Comment by skjnldsv** [comment]
Interesting!
Looking at this, it shouldn't be too complicated.

Though, shall we ever support the v1 ?
Like is there some limitations to it?

**Comment by juliushaertl** [comment]
There is a Limitation as the maximum possible upload size got a file would be 5TB and the chunk size needs to be increased dynamically in case the filesize doesn't fit in 10.000 chunks of the default 10MB chunk size (but that would be for files >100gb). So overall nothing I would consider worth keeping two implementations, especially since this would then still only help for local storage as s3 always had those limitations. Also uploading 100gb in 10 mb chunks doesn't make much sense at all in terms of performance.

Hope that makes it a bit clearer :)

**Comment by skjnldsv** [comment]
How does the front decides which to use then?

**Comment by juliushaertl** [comment]
It does not need to, new api calls are backward compatible with the old backend.

**Comment by juliushaertl** [comment]
Fixed by #925
