### ISSUE TITLE
Set the right Content-Type

### ISSUE THREAD

**Issue by lukasm91** [nextcloud-libraries/nextcloud-upload#995]
We are using nextcloud-upload through [photos](https://github.com/nextcloud/photos/blob/stable28/package.json), and we realized that all uploads that go through this library are creating `PUT`requests with Content-Type as application/x-www-form-urlencoded.

This is certainly not correct for these uploads, and some hosters will just deny such requests because invalid characters are passed as form data.

I suggest something like adding
headers: {'Content-Type': data.type},
to the PUT request in `lib/utils/upload.ts`, or just hardcode `application/octet-stream`.

Since I am not an expert in this at all, there might be better ways to handle this...

**Comment by skjnldsv** [comment]
Hey! :)

Have you experienced any issues? Or is it just a technical debt?

**Comment by lukasm91** [comment]
Hey, thanks for your response!

Yes, our hoster has various SecRule denying these requests. It sees them as application/x-www-form-urlencoded, and rules be enabled based on this Content-Type, e.g. 
https://github.com/SEC642/modsec/blob/master/rules/base_rules/modsecurity_crs_20_protocol_violations.conf#L468

This one, I can disable as a user, but others I cannot. There is another rule, that checks if any form data contains invalid characters, which binary data certainly does.

I also don't think that we should have hosters disabling all affected rules, because they are useful for other parts of the code.

**Comment by skjnldsv** [comment]
@juliushaertl @artonge would it cause issues with the chunked upload?

**Comment by skjnldsv** [comment]
Might be related https://github.com/nextcloud/ios/issues/1942

@tobiasKaminsky @marinofaggiana, do you have any input?

**Comment by artonge** [comment]
> juliushaertl artonge would it cause issues with the chunked upload?

I see no reason for that :thinking:.
